### ISSUE TITLE
Use in native project

### ISSUE THREAD

**Issue by ndozhh** [Ramotion/react-native-circle-menu#9]
It is possible to use the library in Android, in a native project (not Expo), and to work correctly. I tried and it but I got a lot of mistakes.

**Comment by Juriv** [comment]
@NdozHH is it Android ReactNative project or native Android like Java or Kotlin?

**Comment by ndozhh** [comment]
@Juriv in Android project.

**Comment by Juriv** [comment]
@NdozHH you could check this native lib https://github.com/Ramotion/circle-menu-android for android.
We have not tested react-native lib for native project yet

**Comment by ndozhh** [comment]
@Juriv Thanks for answering. I meant that it is a native project of RN (not Expo), and development in Android. But now I get the following error, so I ask if it is possible to use the library in a completely native project.

![image](https://user-images.githubusercontent.com/25773289/35169250-dc6d0d2a-fd29-11e7-9288-0a9a02039d4f.png)
